### ISSUE TITLE
A transit call is not processed outside off a processEvent

### ISSUE THREAD

**Issue by Thierry-girard** [jfayot/dynamic-state-machine#10]
When you are using the transit function outside off a processEvent it is not processed until the next processEvent.

The following test will fail :

    _sm.addState<NiceMock<s0>, Entry>();
    _sm.addState<NiceMock<s1>>();
    _sm.addTransition<s0, e0, s0, &s0::onEvent0>();

    s0* _s0 = _sm.getState<s0>();
    ON_CALL(*_s0, onEvent0(_)).WillByDefault(Invoke([&] () { _s0->transit<s1>(); }));

    _sm.start();
     _s0->transit<s1>();

    ASSERT_TRUE((_sm.checkStates<s1>()));

**Comment by tatayou** [comment]
Hi Jerome

Just some little remarks

- the methods preProcess and postProcess should be declared private instead of public
- the method processEvent should test if the m_topSm is not null. It is done in transit, postEvent and deferEvent

Best regards
JPN

**Comment by jfayot** [comment]
Hi JPN,

Thanks for your review !
I agree with you on both points, even though, for the second one, it should not be strictly needed, as the processEvent can only be called from a completly constructed sm, for which topSm member is correctly set "by design".
But that doesn't hurt, and goes towards good practice, so I'll fix it too.
